nodeLinker: node-modules

packageExtensions:
  baseui@*:
    dependencies:
      styletron-standard: ^3.0.4
  styled-components@*:
    dependencies:
      react-is: ^17.0.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.js
