name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          yarn
          yarn build

      - name: Gatsby Publish
        uses: enriikke/gatsby-gh-pages-action@2.1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
